### ISSUE TITLE
Update options

### ISSUE THREAD

**Issue by moominot** [tanaikech/HtmlFormApp#1]
Hi, I recently find your library and is great!
I'm using it in a webapp but I wanted to update desired row.
I change a little bit your code to do so, maybe you want to add those changes to your library:
at the begining...
`/**
 * Append HTML form data to Spreadsheet.<br>
 * @param {object} object Object including formData returned from HtmlFormObjectParserForGoogleAppsScript_js.
 * @param {number} rowNumber The row number to edit (1-based index). * 
 * @return {object} object Object including Class Spreadsheet, Class Sheet, Class Range of the row put the values, values
 */

function appendFormData(object,row) {
    return new HtmlFormApp(object).appendFormData(row);
}`

And then change de range with:

` rowNumber = row?row:this.lastRow + 1
        range = this.sheet.getRange(rowNumber, 1, values.length, values[0].length);
        range.setValues(values);`

maybe it could be integrated in the same object, but my knowledge is very limited...
I'm learning a lot with all your work! thank you very much

**Comment by tanaikech** [comment]
Thank you for your comment. Now, I noticed from your comment. I apologize for my late response.

Now, I updated HtmlFormApp by reflecting your suggestion as v1.0.2. Please confirm it.

**Comment by manacup** [comment]
great! thank you
